[package]
name = "video_mapper"
version = "0.1.0"
authors = ["LJason <ljason@ljason77.com>"]
edition = "2024"
license-file = "LICENSE"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
percent-encoding = "2"
rand = "0.10"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "local-time"] }
walkdir = "2"

[dependencies.sqlx]
version = "0.9"
default-features = false
features = ["runtime-tokio", "tls-native-tls", "macros", "sqlite"]

[dependencies.tokio]
version = "1"
default-features = false
features = ["rt-multi-thread", "macros"]
